version: '3'

services:
  nginx:
    image: nginx:1.12.2-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/local-disk1/metdna-upload-test:/mnt/data/metdna-upload  # for MEDIA_ROOT of django
      - ./web:/mnt/data/www  # total web code, django and angular
      - /run/uwsgi:/run/uwsgi  # uwsgi unix socket
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80  # port for http
      - 6001:6001  # port for django
