version: '2.2'

services:
  metdna:
    image: onlybelter/rpy2-docker2
    restart: on-failure
    command: python3 run_metDNA.py
    # Limit a container's resources
    # https://docs.docker.com/config/containers/resource_constraints/
    cpus: 8
    mem_limit: 16g
    working_dir: /code
    volumes:
      - ./code:/code
      - /mnt/data/metdna-upload:/mnt/data/metdna-upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1

networks:
  default:
    external:
      name: djangopy35_default
